name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Setup
        run: sudo apt-get install mold libasound2-dev libudev-dev
      - name: Configure Rust
        run: rustup component add clippy
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose --no-deps -- -D warnings
      - name: Run tests
        run: cargo test --verbose
